include ../sources.mak

SIM_SRC=tb_top.v $(BOARD_SRC) $(SIM_CORES_SRC)
SRC=$(BOARD_SRC) $(CORES_SRC)

test: t_data.hex isim

gtk: test
	gtkwave test.vcd

isim: tb_system
	./tb_system

t_data.hex: hex/phy_ping.hex hex/phy_telnet.hex
	sed s/^/1_/g hex/phy_ping.hex > tmp0
	sed s/^/1_/g hex/phy_telnet.hex > tmp1
	cat hex/phy_0.hex tmp0 hex/phy_0.hex tmp1 hex/phy_0.hex > t_data.hex
	rm tmp0 tmp1

cver: $(SRC)
	cver $(SRC)

clean:
	rm -f tb_system verilog.log test.vcd t_data.hex

tb_system: $(SIM_SRC)
	iverilog -o tb_system $(SIM_SRC)

lint: $(SIM_SRC) lint_header.v
	verilator --lint-only -Wall lint_header.v $(SIM_SRC)

.PHONY: clean isim cver gtk
