/* Verilog module instantiation template generated by SCUBA Diamond_1.4_Production (87) */
/* Module Version: 5.4 */
/* Sun Oct 14 22:04:50 2012 */

/* parameterized module instance */
asfifo9 __ (.Data( ), .WrClock( ), .RdClock( ), .WrEn( ), .RdEn( ), 
    .Reset( ), .RPReset( ), .Q( ), .Empty( ), .Full( ));
